options:
  hide_event_toc: False
  hide_mlh_toc: False
  min_resume_age: 17
custom_fields:
 - name: ethnicity
   label: "What is your race/ethnicity?"
   type: select
   required: true
   options:
    - American Indian or Alaskan Native
    - East Asian / Pacific Islander
    - South Asian / Indian
    - Black or African American
    - Hispanic
    - White / Caucasian
    - Multiple ethnicity / Other
    - Prefer not to answer
 - name: graduation_year
   label: "What is your graduation year?"
   required: true
   validate_regex: '\d{4}'
   validate_error: "Your graduation year is not valid (e.g. 2020)"
 - name: dietary_preferences
   label: "What are your dietary preferences?"
   type: multiselect
   options:
    - Vegan
    - Vegetarian
    - Non-Vegetarian
    - Vegetarian (No Egg)
    - Kosher
    - Halal
    - Other (please specify in food allergies question)  
 - name: food_allergies
   label: "What are your food allergies, if any?"
 - name: linkedin_url
   label: 'LinkedIn URL'
   validate_regex: '\A(https:\/\/)?(www.)?linkedin.com\/in\/\S+\z'
   validate_error: 'Your Linkedin URL is invalid. Example format: https://linkedin.com/in/yourprofile'
 - name: github_url
   label: 'GitHub URL'
   validate_regex: '\A(https:\/\/)?(www.)?github.com\/\S+\z'
   validate_error: 'Your Github URL is invalid. Example format: https://github.com/yourprofile'
 - name: other_url
   label: 'Personal Website or Portfolio URL'
 - name: been_to_hackathon
   label: 'Have you been to a hackathon before?'
   type: boolean
   required: True
   toggle_field: how_many_hackathons
 - name: how_many_hackathons
   label: "How many hackathons have you previously attended?"
   type: select
   options:
    - 1
    - 2
    - 3
    - 4
    - 5 or more
   hidden: True
 - name: been_to_hackutd
   label: 'Have you previously attended HackUTD?'
   type: boolean
   required: True
 - name: programming_skills
   label: "Programming Skills (select all that apply)"
   type: multiselect
   options:
    - Web Development
    - Android Development
    - iOS Development
    - Data Science
    - Hardware Hacks
 - name: learn_hackutd
   label: 'What technologies, skills, programming languages, etc. do you want to learn at Hack To School through workshops?'
   type: textarea
 - name: how_did_you_hear
   label: 'How did you learn about Hack To School?'
   type: multiselect
   options:
    - HackUTD Workshops
    - ACM Events and Emails
    - HackUTD Newsletter
    - Word of Mouth
    - Other
   required: True
 - name: fun_question
   label: "Are you excited to attend Hack To School?"
   type: multiselect
   required: True
   options:
    - "Yes"
    - "HELL YES"
